name: LiveCatCam
options:
  bundleIdPrefix: com.kaiser390
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.1.1"
    CURRENT_PROJECT_VERSION: 90
    SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
    SUPPORTS_MACCATALYST: false

targets:
  LiveCatCam:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: Sources/LiveCatCam
        type: group
      - path: SupportFiles/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kaiser390.OLiveCam
        PRODUCT_NAME: OLiveCam
        INFOPLIST_FILE: SupportFiles/Info.plist
        CODE_SIGN_ENTITLEMENTS: SupportFiles/LiveCatCam.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: SXMBC325X9

        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        SWIFT_OBJC_BRIDGING_HEADER: SupportFiles/LiveCatCam-Bridging-Header.h
        OTHER_LDFLAGS: "-lc++"
    dependencies:
      - framework: Frameworks/libsrt.xcframework
        embed: false
    entitlements:
      path: SupportFiles/LiveCatCam.entitlements

schemes:
  OLiveCam:
    build:
      targets:
        LiveCatCam: all
    run:
      config: Debug
    archive:
      config: Release
    profile:
      config: Release
    analyze:
      config: Debug
